name: Lint Python code

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to be configured'
        required: false
        type: string
        default: '3.13'
      requirements-files:
        description: 'Python requirements files with libraries to be installed'
        required: false
        type: string
        default: 'requirements.txt'

jobs:

  lint-python-code:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip
        run: pip3 install --upgrade pip

      - name: Install necessary dependencies
        run: |
          for REQUIREMENTS_FILE in ${{ inputs.requirements-files }}; do
            pip3 install -r "${REQUIREMENTS_FILE}"
          done

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: "-a -v"