name: Sonar Cloud Scan for Python Code

on:
  workflow_call:
    inputs:
      artifact-coverage-name:
        description: 'Artifact coverage name for unit tests'
        required: false
        type: string
        default: 'coverage'
      artifact-coverage-path:
        description: 'Artifact coverage path for unit tests'
        required: false
        type: string
        default: 'coverage.xml'

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact for coverage
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ inputs.artifact-coverage-name }}

      - name: Get repository basename
        run: |
            echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v4.2.1
        with:
          args: >
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ env.REPO_NAME }}
            -Dsonar.organization=${{ github.repository_owner }}
            -Dsonar.python.coverage.reportPaths=${{ inputs.artifact-coverage-path }}
            -Dsonar.test.exclusions=tests/**
            -Dsonar.tests=tests/
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}